name: Build Geode Mod

on:
  workflow_dispatch: # Позволяет запускать сборку вручную по кнопке
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: Compile ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # ========================================================
          # ЗДЕСЬ ТЫ МОЖЕШЬ УКАЗАТЬ КАСТОМНЫЕ РЕПОЗИТОРИИ ПЛАТФОРМЫ
          # ========================================================
          
          # Репозиторий Geode SDK (платформы)
          sdk: 'geode-sdk/geode'  
          sdk-ref: 'main' # Ветка, коммит или тег SDK
          
          # Репозиторий биндингов Geometry Dash
          bindings: 'geode-sdk/bindings' 
          bindings-ref: 'main' # Ветка биндингов
          
          # Репозиторий Geode CLI (утилиты сборки, обычно менять не нужно)
          cli: 'geode-sdk/cli'
          
          # ========================================================

          target: ${{ matrix.config.target }}
          combine: true # Подготовка платформ к объединению в один .geode файл

  package:
    name: Package Final .geode
    runs-on: ubuntu-latest
    needs: build # Ждет, пока соберутся все платформы (Win, Mac, Android)

    steps:
      - name: Combine platforms into one .geode file
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGeodeMod-Latest
          path: ${{ steps.build.outputs.build-output }}
